version: "3.8"

services:
  client:
    build: ./docker
    container_name: nuxt
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - ./app:/nuxt-sample/app
    working_dir: /nuxt-sample
    tty: true
